name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag l8-proxy:$(date +%Y-%m-%d)
    - name: Deploy the Docker container
      run: docker run --name l8-proxy -d --restart always --net host -p 5000:5000 l8-proxy:$(date +%Y-%m-%d)
    
